// biome-ignore-all lint:suspicious/noExplicitAny: AI autogenerated
import { test } from '@playwright/test';

/**
 * Декоратор описывает функцию, которая динамически форматирует имя шага.
 *
 * @param methodArgs Аргументы, переданные в декорируемый метод.
 * @returns Отформатированное имя шага в виде строки.
 *
 * @example
 * // Пример форматтера, использующего первый аргумент метода:
 * const myStepFormatter: StepNameFormatter = (firstArg: any) => `Шаг с параметром: ${firstArg.id}`;
 */
export type StepNameFormatter = (...methodArgs: any[]) => string;

/**
 * Описывает контекстный объект, предоставляемый декораторами методов TC39 Stage 3.
 * Этот тип используется внутри декоратора для работы с новым стандартом декораторов.
 * @internal
 */
type TC39MethodDecoratorContext = {
  kind: 'method';
  name: string | symbol;
  access: {
    get: () => (...args: any[]) => unknown;
  };
  static?: boolean;
  private?: boolean;
  addInitializer?: (initializer: () => void) => void;
  metadata?: Record<string | symbol, unknown>;
};

/**
 * Декоратор `@Step` оборачивает метод класса в вызов `test.step` из Playwright.
 * Позволяет создавать именованные шаги в тестах для лучшей читаемости отчетов.
 *
 * Поддерживает как "старый" синтаксис экспериментальных декораторов (`experimentalDecorators: true`),
 * так и "новый" стандарт ECMAScript декораторов (TC39 Stage 3).
 *
 * @param stepNameOrFormatter - Параметр, определяющий имя шага:
 *   - **Строка**: Статическое имя шага.
 *     ```typescript
 *     @Step("Авторизация пользователя")
 *     async login(user: string, pass: string) { ... }
 *     ```
 *   - **Функция-форматтер (`TStepNameFormatter`)**: Динамически генерирует имя шага.
 *     Функция получает те же аргументы, что и декорируемый метод.
 *     ```typescript
 *     @Step((userId: string, data: any) => `Обновление данных пользователя ${userId}`)
 *     async updateUser(userId: string, data: any) { ... }
 *     ```
 * @returns Возвращает функцию-декоратор.
 *
 * @example
 * ```typescript
 * import { Step, TStepNameFormatter } from './path/to/decorators'; // Укажите правильный путь
 *
 * class UserApi {
 *   @Step("Получение информации о пользователе по ID")
 *   async getUserById(userId: string) {
 *     // ... логика запроса ...
 *     return { id: userId, name: "Тестовый Пользователь" };
 *   }
 *
 *   @Step((itemId: number, quantity: number) => `Добавление товара ${itemId} в количестве ${quantity} в корзину`)
 *   async addItemToCart(itemId: number, quantity: number) {
 *     // ... логика добавления в корзину ...
 *     return { success: true, itemId, quantity };
 *   }
 * }
 * ```
 */
// eslint-disable-next-line @typescript-eslint/naming-convention
export function Step(stepNameOrFormatter: string | StepNameFormatter): (...args: any[]) => any {
  if (typeof stepNameOrFormatter !== 'string' && typeof stepNameOrFormatter !== 'function') {
    throw new Error('@Step decorator requires a step name (string) or a formatter function as its argument.');
  }

  // eslint-disable-next-line max-params
  return function actualDecorator(
    valueOrTarget: any,
    contextOrPropertyKey: string | symbol | TC39MethodDecoratorContext,
    descriptor?: PropertyDescriptor,
  ): any {
    let originalMethod: (...args: any[]) => unknown;
    let methodNameForErrorContext: string;
    let isTC39Decorator = false;

    if (
      typeof contextOrPropertyKey === 'object' &&
      contextOrPropertyKey !== null &&
      (contextOrPropertyKey as TC39MethodDecoratorContext).kind === 'method'
    ) {
      isTC39Decorator = true;

      const context = contextOrPropertyKey as TC39MethodDecoratorContext;

      originalMethod = valueOrTarget as (...args: any[]) => unknown;
      methodNameForErrorContext = String(context.name);

      if (typeof originalMethod !== 'function') {
        const errMsg = 'TC39 Decorator: Expected first argument (value) to be a function for a method decorator.';
        throw new Error(errMsg);
      }
    } else if (descriptor && typeof descriptor.value === 'function' && typeof contextOrPropertyKey === 'string') {
      originalMethod = descriptor.value as (...args: any[]) => unknown;
      methodNameForErrorContext = String(contextOrPropertyKey);
    } else {
      const targetName =
        valueOrTarget?.constructor?.name ||
        (typeof valueOrTarget === 'function' ? valueOrTarget.name : 'UnknownTarget');

      const propKeyName = String(contextOrPropertyKey);
      const errMsg = `@Step decorator applied with an unrecognized signature or to an unsupported element. Target/Value type: ${targetName}, PropertyKey/Context: ${propKeyName}.`;

      throw new Error(errMsg);
    }

    const wrappedMethod = function (this: any, ...args: any[]): unknown {
      let stepName: string;

      if (typeof stepNameOrFormatter === 'function') {
        try {
          stepName = stepNameOrFormatter.apply(this, args);
        } catch (e: unknown) {
          const errorMessage = e instanceof Error ? e.message : String(e);
          console.warn(
            `@Step: Error in step name formatter for '${methodNameForErrorContext}'. Error: ${errorMessage}`,
          );
          stepName = `Error in step formatter for ${methodNameForErrorContext}`;
        }
      } else {
        stepName = stepNameOrFormatter as string;
      }

      return test.step(stepName, async () => {
        return originalMethod.apply(this, args);
      });
    };

    if (isTC39Decorator) {
      return wrappedMethod;
    } else if (descriptor) {
      descriptor.value = wrappedMethod;

      return descriptor;
    }

    throw new Error(
      'Internal @Step decorator error: Failed to apply decorator modification. Decorator type could not be determined or handled.',
    );
  };
}
